# AlertManager告警管理配置
global:
  # SMTP配置
  smtp_smarthost: '${SMTP_HOST:smtp.gmail.com:587}'
  smtp_from: '${ALERT_EMAIL_FROM:codenavigator@example.com}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  
  # 其他全局配置
  resolve_timeout: 5m
  http_config:
    tls_config:
      insecure_skip_verify: true

# 路由配置
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'web.hook.default'
  routes:
    # 关键告警 - 立即通知
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
      
    # 警告级别告警
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 1h
      
    # 业务告警
    - match_re:
        alertname: '.*Business.*|.*User.*|.*AI.*'
      receiver: 'business-alerts'
      group_wait: 1m
      repeat_interval: 30m

# 接收器配置
receivers:
  # 默认接收器
  - name: 'web.hook.default'
    webhook_configs:
      - url: 'http://localhost:5001/alerts'
        send_resolved: true

  # 关键告警接收器
  - name: 'critical-alerts'
    email_configs:
      - to: '${CRITICAL_ALERT_EMAIL:admin@codenavigator.com}'
        subject: '[CRITICAL] CodeNavigator Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Service: {{ .CommonLabels.service }}
          
          Details:
          {{ range .Alerts }}
          - Alert: {{ .Annotations.summary }}
          - Description: {{ .Annotations.description }}
          - Time: {{ .StartsAt }}
          {{ end }}
          
          Dashboard: http://grafana:3000
        headers:
          X-Priority: '1'
    webhook_configs:
      - url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: 'CodeNavigator Critical Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Service:* {{ .CommonLabels.service }}
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        send_resolved: true

  # 警告告警接收器
  - name: 'warning-alerts'
    email_configs:
      - to: '${WARNING_ALERT_EMAIL:dev@codenavigator.com}'
        subject: '[WARNING] CodeNavigator Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Service: {{ .CommonLabels.service }}
          
          Details:
          {{ range .Alerts }}
          - Alert: {{ .Annotations.summary }}
          - Description: {{ .Annotations.description }}
          - Time: {{ .StartsAt }}
          {{ end }}
        headers:
          X-Priority: '3'
    webhook_configs:
      - url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-warning'
        title: 'CodeNavigator Warning Alert'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          {{ range .Alerts }}
          *Summary:* {{ .Annotations.summary }}
          {{ end }}
        send_resolved: true

  # 业务告警接收器
  - name: 'business-alerts'
    email_configs:
      - to: '${BUSINESS_ALERT_EMAIL:business@codenavigator.com}'
        subject: '[BUSINESS] CodeNavigator Business Alert: {{ .GroupLabels.alertname }}'
        body: |
          Business Alert: {{ .GroupLabels.alertname }}
          Service: {{ .CommonLabels.service }}
          
          Business Impact:
          {{ range .Alerts }}
          - Issue: {{ .Annotations.summary }}
          - Details: {{ .Annotations.description }}
          - Time: {{ .StartsAt }}
          {{ end }}
          
          Please check the business metrics dashboard.
        headers:
          X-Priority: '2'

# 抑制规则
inhibit_rules:
  # 如果应用下线，抑制其他相关告警
  - source_match:
      alertname: 'ApplicationDown'
    target_match:
      service: 'codenavigator'
    equal: ['service', 'instance']
    
  # 如果数据库下线，抑制数据库相关告警
  - source_match:
      alertname: 'MySQLDown'
    target_match_re:
      alertname: 'MySQL.*|Database.*'
    equal: ['instance']
    
  # 如果Redis下线，抑制Redis相关告警
  - source_match:
      alertname: 'RedisDown'
    target_match_re:
      alertname: 'Redis.*'
    equal: ['instance']

# 模板配置
templates:
  - '/etc/alertmanager/templates/*.tmpl'