# Prometheus监控配置
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'codenavigator-prod'
    environment: 'production'

# 告警规则配置
rule_files:
  - "alerts/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 监控目标配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # CodeNavigator应用监控
  - job_name: 'codenavigator-app'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: app:8080

  # MySQL监控
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 30s
    params:
      collect[]:
        - info_schema.innodb_metrics
        - info_schema.processlist
        - info_schema.query_response_time
        - slave_status
        - binlog_size
        - perf_schema.tablelocks
        - perf_schema.file_events
        - perf_schema.eventswaits
        - perf_schema.indexiowaits
        - perf_schema.tableiowaits
        - auto_increment.columns
        - binlog_size
        - global_status
        - global_variables
        - slave_status

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Node系统监控
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '${1}'

  # Docker容器监控
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # JVM详细监控
  - job_name: 'jvm-micrometer'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 10s
    metrics_path: /actuator/prometheus
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'jvm_.*'
        target_label: component
        replacement: 'jvm'

# 存储配置
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# 远程写入配置（可选，用于长期存储）
# remote_write:
#   - url: "http://thanos-receive:19291/api/v1/receive"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500