# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_navigator_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: password
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      
  thymeleaf:
    cache: false

# 开发环境日志级别
logging:
  level:
    com.codenavigator: DEBUG
    org.springframework: INFO
    root: INFO

# 开发环境AI配置
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:}
      model-name: gpt-4
      temperature: 0.3